// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs4z6WhFTkD5FzJVtNFMOPx_Qfsi3rauo',
    appId: '1:1020059850436:web:9c03af387b6431d5299b91',
    messagingSenderId: '1020059850436',
    projectId: 'portfolio-4f2c6',
    authDomain: 'portfolio-4f2c6.firebaseapp.com',
    storageBucket: 'portfolio-4f2c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwzEZB1OMZKAh5VSNMuo0FC9lDQ5I5b_M',
    appId: '1:1020059850436:android:2f9422fb448921d5299b91',
    messagingSenderId: '1020059850436',
    projectId: 'portfolio-4f2c6',
    storageBucket: 'portfolio-4f2c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8mZ8fK7xBL0Fze7cQMaTOkvlGa7Teox0',
    appId: '1:1020059850436:ios:98cf131d2ef39070299b91',
    messagingSenderId: '1020059850436',
    projectId: 'portfolio-4f2c6',
    storageBucket: 'portfolio-4f2c6.appspot.com',
    iosBundleId: 'com.example.portfolio',
  );
}
